from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "output"
RESUME_PATH = DATA_DIR / "resume.pdf"
SKILLS_PATH = DATA_DIR / "skills.csv"
EXCEL_OUTPUT_PATH = OUTPUT_DIR / "jobs.xlsx"

GREENHOUSE_COMPANIES = [
    "xai",
    "scaleai",
    "datadog",
    "figma",
    # Plaid's former Greenhouse board currently returns 404. Keep it disabled
    # until an official supported job source is configured.
    "reddit",
    "discord",
    "affirm",
]

LEVER_COMPANIES = [
    "spotify",
    "findigs",
    "sambatv",
    "analyticpartners",
]

ASHBY_COMPANIES = [
    "ramp",
    "linear",
    "vanta",
    "cohere",
    "harvey",
    "cursor",
    "openai",
    "notion",
    "watershed",
    "modal",
    "perplexity",
    "benchling",
    "insitro",
]

TARGET_JOB_KEYWORDS = [
    "data analyst",
    "data scientist",
    "business analyst",
    "product analyst",
    "biostatistician",
    "biostatistics",
    "health data",
    "health analytics",
    "clinical data",
    "machine learning engineer",
    "research engineer",
    "analytics",
    "data science",
    "decision science",
    "decision scientist",
    "insights analyst",
    "quantitative analyst",
    "statistical analyst",
    "research analyst",
    "business intelligence analyst",
    "bi analyst",
    "operations analyst",
    "strategy analyst",
    "analytics analyst",
    "ml engineer",
    "ai engineer",
    "data engineer",
    "statistical programmer",
    "clinical data scientist",
    "health data scientist",
    "business systems analyst",
]

EXCLUDED_JOB_KEYWORDS = [
    "senior",
    "sr.",
    "sr",
    "staff",
    "principal",
    "director",
    "manager",
    "lead",
    "head of",
    "vice president",
    "vp",
    "chief",
    "tutor",
    "account executive",
    "sales",
    "marketing",
    "recruiter",
    "research scientist",
    "phd",
    "postdoc",
    "postdoctoral",
    "it operations analyst",
    "software engineer",
]

ALLOWED_LOCATION_KEYWORDS = [
    "united states",
    "usa",
    "mainland china",
    "china",
    "hong kong sar",
    "hong kong",
    "singapore",
    "beijing",
    "shanghai",
    "shenzhen",
    "guangzhou",
    "hangzhou",
]

US_STATE_NAMES = [
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "california",
    "colorado",
    "connecticut",
    "delaware",
    "district of columbia",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "north carolina",
    "north dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode island",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west virginia",
    "wisconsin",
    "wyoming",
]

US_STATE_ABBREVIATIONS = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
    "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
    "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
    "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
    "WY",
]

US_CITY_NAMES = [
    "San Francisco",
    "Seattle",
    "New York City",
    "New York",
    "Boston",
    "Los Angeles",
    "San Diego",
    "Chicago",
    "Austin",
    "Dallas",
    "Houston",
    "Washington DC",
    "Washington, DC",
    "Atlanta",
    "Denver",
    "Miami",
    "Philadelphia",
    "Pittsburgh",
    "Portland",
    "Phoenix",
    "Raleigh",
    "Charlotte",
    "Nashville",
    "Salt Lake City",
    "San Jose",
    "Palo Alto",
    "Mountain View",
    "Sunnyvale",
    "Redwood City",
    "Menlo Park",
    "Cambridge",
    "Bellevue",
    "Redmond",
    "Santa Clara",
    "Cupertino",
    "Oakland",
    "Sacramento",
    "Irvine",
    "Boulder",
    "Minneapolis",
    "Detroit",
    "Columbus",
]

MINIMUM_MATCH_SCORE = 20
MAX_REQUIRED_EXPERIENCE_YEARS = 2
SKILL_MATCH_DEBUG = True
TOP_AI_MATCH_COUNT = 5
AI_MATCH_MAX_WORKERS = 4
SPONSORSHIP_MAX_WORKERS = 4
DECISION_MAX_WORKERS = 4
